// packages/wrappers/react/src/InputField.tsx
/**
 * @package @kds/react
 * @component InputField
 * @description React component wrapper for kds-input-field web component
 */

import React, { forwardRef, useRef, useEffect, useImperativeHandle } from 'react';
import type { InputFieldType } from '@kds/web-components';

export interface InputFieldProps {
  /** Visual variant. Default: 'default'. */
  type?: InputFieldType;

  /** Label text above the input. Empty = no label. */
  label?: string;

  /** Helper/hint text below. In destructive state, styled as error message. */
  hint?: string;

  /** Placeholder text for the native input. */
  placeholder?: string;

  /** Current input value (controlled). */
  value?: string;

  /** Default value (uncontrolled). */
  defaultValue?: string;

  /** HTML name attribute for form participation. */
  name?: string;

  /** HTML input type (text, email, password, number, tel, url…). Default: 'text'. */
  inputType?: string;

  /** Error/destructive state. Red border + alert icon. */
  destructive?: boolean;

  /** Disabled state. */
  disabled?: boolean;

  /** Show leading icon slot. */
  leadingIcon?: boolean;

  /** Show help icon button on the right. */
  helpIcon?: boolean;

  /** Text prefix for type='leading-text'. E.g. 'http://', '$'. */
  leadingText?: string;

  /** HTML required attribute. */
  required?: boolean;

  /** ARIA label (used when label prop is not set). */
  'aria-label'?: string;

  /** Fired on every keystroke. */
  onKdsInput?: (e: CustomEvent<{ value: string }>) => void;

  /** Fired on blur after value change. */
  onKdsChange?: (e: CustomEvent<{ value: string }>) => void;

  /** Fired when help icon is clicked. */
  onKdsHelpClick?: (e: CustomEvent<void>) => void;

  /** Leading icon element (rendered into leading-icon slot). */
  leadingIconContent?: React.ReactNode;

  /** Leading dropdown element (for type='leading-dropdown'). */
  leadingDropdownContent?: React.ReactNode;

  /** Trailing dropdown element (for type='trailing-dropdown'). */
  trailingDropdownContent?: React.ReactNode;

  className?: string;
  style?: React.CSSProperties;
  id?: string;
}

export const InputField = forwardRef<HTMLElement, InputFieldProps>(
  (
    {
      type = 'default',
      label,
      hint,
      placeholder,
      value,
      defaultValue,
      name,
      inputType,
      destructive,
      disabled,
      leadingIcon,
      helpIcon,
      leadingText,
      required,
      'aria-label': ariaLabel,
      onKdsInput,
      onKdsChange,
      onKdsHelpClick,
      leadingIconContent,
      leadingDropdownContent,
      trailingDropdownContent,
      className,
      style,
      id,
    },
    ref
  ) => {
    const elementRef = useRef<HTMLElement>(null);

    useImperativeHandle(ref, () => elementRef.current!);

    useEffect(() => {
      const el = elementRef.current;
      if (!el) return;

      const handleInput = (e: Event) => onKdsInput?.(e as CustomEvent<{ value: string }>);
      const handleChange = (e: Event) => onKdsChange?.(e as CustomEvent<{ value: string }>);
      const handleHelpClick = (e: Event) => onKdsHelpClick?.(e as CustomEvent<void>);

      el.addEventListener('kds-input', handleInput);
      el.addEventListener('kds-change', handleChange);
      el.addEventListener('kds-help-click', handleHelpClick);

      return () => {
        el.removeEventListener('kds-input', handleInput);
        el.removeEventListener('kds-change', handleChange);
        el.removeEventListener('kds-help-click', handleHelpClick);
      };
    }, [onKdsInput, onKdsChange, onKdsHelpClick]);

    // Sync value prop to web component imperatively (controlled mode)
    useEffect(() => {
      const el = elementRef.current as any;
      if (el && value !== undefined) {
        el.value = value;
      }
    }, [value]);

    return React.createElement(
      'kds-input-field' as any,
      {
        ref: elementRef,
        id,
        class: className,
        style,
        type,
        label: label ?? undefined,
        hint: hint ?? undefined,
        placeholder: placeholder ?? undefined,
        value: value ?? defaultValue ?? undefined,
        name: name ?? undefined,
        'input-type': inputType ?? undefined,
        destructive: destructive || undefined,
        disabled: disabled || undefined,
        'leading-icon': leadingIcon || undefined,
        'help-icon': helpIcon || undefined,
        'leading-text': leadingText ?? undefined,
        required: required || undefined,
        'aria-label': ariaLabel ?? undefined,
      },
      leadingIconContent
        ? React.createElement('span', { slot: 'leading-icon', key: 'leading-icon' }, leadingIconContent)
        : null,
      leadingDropdownContent
        ? React.createElement('div', { slot: 'leading-dropdown', key: 'leading-dropdown' }, leadingDropdownContent)
        : null,
      trailingDropdownContent
        ? React.createElement('div', { slot: 'trailing-dropdown', key: 'trailing-dropdown' }, trailingDropdownContent)
        : null
    );
  }
);

InputField.displayName = 'InputField';

// packages/wrappers/angular/src/input-field.component.ts
/**
 * @package @kds/angular
 * @component KdsInputFieldComponent
 * @description Angular component wrapper for kds-input-field web component
 */

import {
  Component,
  Input,
  Output,
  EventEmitter,
  ViewChild,
  ElementRef,
  AfterViewInit,
  OnChanges,
  SimpleChanges,
  OnDestroy,
  CUSTOM_ELEMENTS_SCHEMA
} from '@angular/core';
import type { InputFieldType } from '@kds/web-components';

/**
 * Angular wrapper for the Input Field web component
 *
 * @example
 * ```typescript
 * import { KdsInputFieldComponent } from '@kds/angular';
 *
 * @Component({
 *   selector: 'app-example',
 *   template: `
 *     <kds-input-field-wrapper
 *       label="Email"
 *       hint="This is a hint text."
 *       placeholder="olivia@untitledui.com"
 *       inputType="email"
 *       [value]="emailValue"
 *       (kdsInput)="onInput($event)"
 *     ></kds-input-field-wrapper>
 *   `
 * })
 * export class AppComponent {
 *   emailValue = '';
 *   onInput(e: CustomEvent<{value:string}>) { this.emailValue = e.detail.value; }
 * }
 * ```
 */
@Component({
  selector: 'kds-input-field-wrapper',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <kds-input-field
      #inputFieldElement
      [attr.type]="type"
      [attr.label]="label || null"
      [attr.hint]="hint || null"
      [attr.placeholder]="placeholder || null"
      [attr.name]="name || null"
      [attr.input-type]="inputType || null"
      [attr.leading-text]="leadingText || null"
      [attr.destructive]="destructive ? '' : null"
      [attr.disabled]="disabled ? '' : null"
      [attr.leading-icon]="leadingIcon ? '' : null"
      [attr.help-icon]="helpIcon ? '' : null"
      [attr.required]="required ? '' : null"
    >
      <ng-content select="[slot=leading-icon]"></ng-content>
      <ng-content select="[slot=leading-dropdown]"></ng-content>
      <ng-content select="[slot=trailing-dropdown]"></ng-content>
    </kds-input-field>
  `,
})
export class KdsInputFieldComponent implements AfterViewInit, OnChanges, OnDestroy {
  @ViewChild('inputFieldElement') inputFieldElement!: ElementRef<HTMLElement>;

  /** Visual variant. Default: 'default'. */
  @Input() type: InputFieldType = 'default';

  /** Label text above the input. */
  @Input() label: string = '';

  /** Helper/hint text below. In destructive state, styled as error message. */
  @Input() hint: string = '';

  /** Placeholder text for the native input. */
  @Input() placeholder: string = '';

  /** Current input value (for programmatic updates). */
  @Input() value: string = '';

  /** HTML name attribute. */
  @Input() name: string = '';

  /** HTML input type (text, email, password, number…). Default: 'text'. */
  @Input() inputType: string = 'text';

  /** Error/destructive state. */
  @Input() destructive: boolean = false;

  /** Disabled state. */
  @Input() disabled: boolean = false;

  /** Show leading icon slot. */
  @Input() leadingIcon: boolean = false;

  /** Show help icon button. */
  @Input() helpIcon: boolean = false;

  /** Text prefix for type='leading-text'. */
  @Input() leadingText: string = '';

  /** HTML required attribute. */
  @Input() required: boolean = false;

  /** Emitted on every keystroke. */
  @Output() kdsInput = new EventEmitter<CustomEvent<{ value: string }>>();

  /** Emitted on blur after value change. */
  @Output() kdsChange = new EventEmitter<CustomEvent<{ value: string }>>();

  /** Emitted when help icon is clicked. */
  @Output() kdsHelpClick = new EventEmitter<CustomEvent<void>>();

  private _handleInput = (e: Event) =>
    this.kdsInput.emit(e as CustomEvent<{ value: string }>);
  private _handleChange = (e: Event) =>
    this.kdsChange.emit(e as CustomEvent<{ value: string }>);
  private _handleHelpClick = (e: Event) =>
    this.kdsHelpClick.emit(e as CustomEvent<void>);

  ngAfterViewInit(): void {
    const el = this.inputFieldElement.nativeElement;
    el.addEventListener('kds-input', this._handleInput);
    el.addEventListener('kds-change', this._handleChange);
    el.addEventListener('kds-help-click', this._handleHelpClick);
    this._syncValue();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['value'] && this.inputFieldElement) {
      this._syncValue();
    }
  }

  ngOnDestroy(): void {
    const el = this.inputFieldElement?.nativeElement;
    if (!el) return;
    el.removeEventListener('kds-input', this._handleInput);
    el.removeEventListener('kds-change', this._handleChange);
    el.removeEventListener('kds-help-click', this._handleHelpClick);
  }

  private _syncValue(): void {
    const el = this.inputFieldElement?.nativeElement as any;
    if (el && this.value !== undefined) {
      el.value = this.value;
    }
  }
}
