// packages/wrappers/react/src/Toggle.tsx
/**
 * @package @kds/react
 * @component Toggle
 * @description React wrapper for kds-toggle web component
 */

import React, { useEffect, useRef, forwardRef } from 'react';
import type { ToggleSize } from '@kds/web-components';
import '@kds/web-components';

export interface ToggleProps {
  /**
   * Toggle size
   * @default 'sm'
   */
  size?: ToggleSize;

  /**
   * Whether the toggle is pressed (on)
   * @default false
   */
  pressed?: boolean;

  /**
   * Disabled state
   * @default false
   */
  disabled?: boolean;

  /**
   * Supporting/helper text below the label
   */
  supportingText?: string;

  /**
   * Name attribute for form submission
   */
  name?: string;

  /**
   * Value attribute for form submission
   * @default 'on'
   */
  value?: string;

  /**
   * ARIA label for accessibility
   */
  ariaLabel?: string;

  /**
   * ARIA described-by for help text
   */
  ariaDescribedBy?: string;

  /**
   * Change event handler
   */
  onChange?: (event: CustomEvent) => void;

  /**
   * Focus event handler
   */
  onFocus?: (event: CustomEvent) => void;

  /**
   * Blur event handler
   */
  onBlur?: (event: CustomEvent) => void;

  /**
   * Toggle label (text content)
   */
  children?: React.ReactNode;

  /**
   * Additional CSS classes
   */
  className?: string;

  /**
   * Additional styles
   */
  style?: React.CSSProperties;
}

/**
 * Toggle component wrapper for React
 *
 * @example
 * ```tsx
 * import { Toggle } from '@kds/react';
 * import '@kds/web-components/tokens.css';
 *
 * function App() {
 *   const [pressed, setPressed] = React.useState(false);
 *
 *   return (
 *     <Toggle
 *       size="sm"
 *       pressed={pressed}
 *       onChange={(e) => setPressed(e.detail.pressed)}
 *     >
 *       Remember me
 *     </Toggle>
 *   );
 * }
 * ```
 */
export const Toggle = forwardRef<HTMLElement, ToggleProps>(
  (
    {
      size = 'sm',
      pressed = false,
      disabled = false,
      supportingText,
      name,
      value = 'on',
      ariaLabel,
      ariaDescribedBy,
      onChange,
      onFocus,
      onBlur,
      children,
      className,
      style,
    },
    ref
  ) => {
    const toggleRef = useRef<HTMLElement>(null);

    useEffect(() => {
      if (ref && toggleRef.current) {
        if (typeof ref === 'function') {
          ref(toggleRef.current);
        } else {
          (ref as React.MutableRefObject<HTMLElement | null>).current = toggleRef.current;
        }
      }
    }, [ref]);

    useEffect(() => {
      const toggle = toggleRef.current;
      if (!toggle || !onChange) return;

      const handleChange = (event: Event) => {
        onChange(event as CustomEvent);
      };

      toggle.addEventListener('kds-toggle-change', handleChange);

      return () => {
        toggle.removeEventListener('kds-toggle-change', handleChange);
      };
    }, [onChange]);

    useEffect(() => {
      const toggle = toggleRef.current;
      if (!toggle || !onFocus) return;

      const handleFocus = (event: Event) => {
        onFocus(event as CustomEvent);
      };

      toggle.addEventListener('kds-toggle-focus', handleFocus);

      return () => {
        toggle.removeEventListener('kds-toggle-focus', handleFocus);
      };
    }, [onFocus]);

    useEffect(() => {
      const toggle = toggleRef.current;
      if (!toggle || !onBlur) return;

      const handleBlur = (event: Event) => {
        onBlur(event as CustomEvent);
      };

      toggle.addEventListener('kds-toggle-blur', handleBlur);

      return () => {
        toggle.removeEventListener('kds-toggle-blur', handleBlur);
      };
    }, [onBlur]);

    return React.createElement(
      'kds-toggle',
      {
        ref: toggleRef,
        size,
        pressed: pressed ? '' : undefined,
        disabled: disabled ? '' : undefined,
        'supporting-text': supportingText,
        name,
        value,
        'aria-label': ariaLabel,
        'aria-describedby': ariaDescribedBy,
        class: className,
        style,
      },
      children
    );
  }
);

Toggle.displayName = 'Toggle';

// packages/wrappers/angular/src/toggle.component.ts
/**
 * @package @kds/angular
 * @component KdsToggleComponent
 * @description Angular component wrapper for kds-toggle web component
 */

import {
  Component,
  Input,
  Output,
  EventEmitter,
  ViewChild,
  ElementRef,
  AfterViewInit,
  OnDestroy,
  CUSTOM_ELEMENTS_SCHEMA
} from '@angular/core';
import type { ToggleSize } from '@kds/web-components';

/**
 * Angular wrapper for the Toggle web component
 *
 * @example
 * ```typescript
 * import { KdsToggleComponent } from '@kds/angular';
 *
 * @Component({
 *   selector: 'app-example',
 *   template: `
 *     <kds-toggle-wrapper
 *       size="sm"
 *       [pressed]="isPressed"
 *       (toggleChange)="handleChange($event)"
 *     >
 *       Remember me
 *     </kds-toggle-wrapper>
 *   `
 * })
 * export class ExampleComponent {
 *   isPressed = false;
 *
 *   handleChange(event: CustomEvent) {
 *     this.isPressed = event.detail.pressed;
 *   }
 * }
 * ```
 */
@Component({
  selector: 'kds-toggle-wrapper',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <kds-toggle
      #toggleElement
      [attr.size]="size"
      [attr.pressed]="pressed ? '' : null"
      [attr.disabled]="disabled ? '' : null"
      [attr.supporting-text]="supportingText"
      [attr.name]="name"
      [attr.value]="value"
      [attr.aria-label]="ariaLabel"
      [attr.aria-describedby]="ariaDescribedBy"
    >
      <ng-content></ng-content>
    </kds-toggle>
  `,
  styles: [`
    :host {
      display: inline-flex;
    }
  `]
})
export class KdsToggleComponent implements AfterViewInit, OnDestroy {
  @ViewChild('toggleElement', { static: true }) toggleElement!: ElementRef<HTMLElement>;

  /**
   * Toggle size
   * @default 'sm'
   */
  @Input() size: ToggleSize = 'sm';

  /**
   * Whether the toggle is pressed (on)
   * @default false
   */
  @Input() pressed: boolean = false;

  /**
   * Disabled state
   * @default false
   */
  @Input() disabled: boolean = false;

  /**
   * Supporting/helper text below the label
   */
  @Input() supportingText?: string;

  /**
   * Name attribute for form submission
   */
  @Input() name?: string;

  /**
   * Value attribute for form submission
   * @default 'on'
   */
  @Input() value: string = 'on';

  /**
   * ARIA label for accessibility
   */
  @Input() ariaLabel?: string;

  /**
   * ARIA described-by for help text
   */
  @Input() ariaDescribedBy?: string;

  /**
   * Emits when the toggle value changes
   */
  @Output() toggleChange = new EventEmitter<CustomEvent>();

  /**
   * Emits when the toggle receives focus
   */
  @Output() toggleFocus = new EventEmitter<CustomEvent>();

  /**
   * Emits when the toggle loses focus
   */
  @Output() toggleBlur = new EventEmitter<CustomEvent>();

  private changeListener?: (event: Event) => void;
  private focusListener?: (event: Event) => void;
  private blurListener?: (event: Event) => void;

  ngAfterViewInit(): void {
    this.changeListener = (event: Event) => {
      this.toggleChange.emit(event as CustomEvent);
    };

    this.focusListener = (event: Event) => {
      this.toggleFocus.emit(event as CustomEvent);
    };

    this.blurListener = (event: Event) => {
      this.toggleBlur.emit(event as CustomEvent);
    };

    this.toggleElement.nativeElement.addEventListener(
      'kds-toggle-change',
      this.changeListener
    );

    this.toggleElement.nativeElement.addEventListener(
      'kds-toggle-focus',
      this.focusListener
    );

    this.toggleElement.nativeElement.addEventListener(
      'kds-toggle-blur',
      this.blurListener
    );
  }

  ngOnDestroy(): void {
    if (this.changeListener) {
      this.toggleElement.nativeElement.removeEventListener(
        'kds-toggle-change',
        this.changeListener
      );
    }

    if (this.focusListener) {
      this.toggleElement.nativeElement.removeEventListener(
        'kds-toggle-focus',
        this.focusListener
      );
    }

    if (this.blurListener) {
      this.toggleElement.nativeElement.removeEventListener(
        'kds-toggle-blur',
        this.blurListener
      );
    }
  }
}
