// packages/wrappers/angular/src/button-group.component.ts
/**
 * @package @kds/angular
 * @component KdsButtonGroupComponent, KdsButtonGroupItemComponent
 * @description Angular component wrappers for kds-button-group web components
 */

import {
  Component,
  Input,
  Output,
  EventEmitter,
  ViewChild,
  ElementRef,
  AfterViewInit,
  OnDestroy,
  CUSTOM_ELEMENTS_SCHEMA
} from '@angular/core';
import type { ButtonGroupItemIcon } from '@kds/web-components';

/**
 * Angular wrapper for the Button Group container
 *
 * @example
 * ```html
 * <kds-button-group-wrapper ariaLabel="View options">
 *   <kds-button-group-item-wrapper [selected]="true">Tab 1</kds-button-group-item-wrapper>
 *   <kds-button-group-item-wrapper>Tab 2</kds-button-group-item-wrapper>
 * </kds-button-group-wrapper>
 * ```
 */
@Component({
  selector: 'kds-button-group-wrapper',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <kds-button-group
      #groupElement
      [attr.aria-label]="ariaLabel"
    >
      <ng-content></ng-content>
    </kds-button-group>
  `,
  styles: [`
    :host {
      display: inline-block;
    }
  `]
})
export class KdsButtonGroupComponent {
  @ViewChild('groupElement', { static: true }) groupElement!: ElementRef<HTMLElement>;

  /**
   * ARIA label for the group
   */
  @Input() ariaLabel?: string;
}

/**
 * Angular wrapper for a Button Group item
 *
 * @example
 * ```html
 * <kds-button-group-item-wrapper
 *   [selected]="true"
 *   icon="leading"
 *   (itemClick)="handleClick($event)"
 * >
 *   <svg slot="icon" ...></svg>
 *   Tab Label
 * </kds-button-group-item-wrapper>
 * ```
 */
@Component({
  selector: 'kds-button-group-item-wrapper',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <kds-button-group-item
      #itemElement
      [attr.selected]="selected || null"
      [attr.icon]="icon"
      [attr.disabled]="disabled || null"
      [attr.value]="value"
      [attr.aria-label]="ariaLabel"
    >
      <ng-content></ng-content>
    </kds-button-group-item>
  `,
  styles: [`
    :host {
      display: contents;
    }
  `]
})
export class KdsButtonGroupItemComponent implements AfterViewInit, OnDestroy {
  @ViewChild('itemElement', { static: true }) itemElement!: ElementRef<HTMLElement>;

  /**
   * Whether this item is selected
   * @default false
   */
  @Input() selected = false;

  /**
   * Icon variant
   * @default 'none'
   */
  @Input() icon: ButtonGroupItemIcon = 'none';

  /**
   * Whether the item is disabled
   * @default false
   */
  @Input() disabled = false;

  /**
   * Value for selection tracking
   */
  @Input() value?: string;

  /**
   * ARIA label (required for icon-only)
   */
  @Input() ariaLabel?: string;

  /**
   * Emits when the item is clicked
   */
  @Output() itemClick = new EventEmitter<CustomEvent>();

  private clickListener?: (event: Event) => void;

  ngAfterViewInit(): void {
    this.clickListener = (event: Event) => {
      this.itemClick.emit(event as CustomEvent);
    };

    this.itemElement.nativeElement.addEventListener(
      'kds-button-group-item-click',
      this.clickListener
    );
  }

  ngOnDestroy(): void {
    if (this.clickListener) {
      this.itemElement.nativeElement.removeEventListener(
        'kds-button-group-item-click',
        this.clickListener
      );
    }
  }
}

// packages/wrappers/react/src/ButtonGroup.tsx
/**
 * @package @kds/react
 * @component ButtonGroup, ButtonGroupItem
 * @description React component wrappers for kds-button-group web components
 */

import React, { forwardRef, useRef, useEffect } from 'react';
import type { ButtonGroupItemIcon } from '@kds/web-components';

export interface ButtonGroupProps {
  /**
   * ARIA label for the group
   */
  ariaLabel?: string;

  /**
   * Group content (ButtonGroupItem children)
   */
  children?: React.ReactNode;

  /**
   * Additional CSS classes
   */
  className?: string;

  /**
   * Additional styles
   */
  style?: React.CSSProperties;
}

export const ButtonGroup = forwardRef<HTMLElement, ButtonGroupProps>(
  ({ ariaLabel, children, className, style }, ref) => {
    const groupRef = useRef<HTMLElement>(null);

    useEffect(() => {
      if (ref && groupRef.current) {
        if (typeof ref === 'function') {
          ref(groupRef.current);
        } else {
          (ref as React.MutableRefObject<HTMLElement | null>).current = groupRef.current;
        }
      }
    }, [ref]);

    return React.createElement(
      'kds-button-group',
      {
        ref: groupRef,
        'aria-label': ariaLabel,
        class: className,
        style,
      },
      children
    );
  }
);

ButtonGroup.displayName = 'ButtonGroup';

export interface ButtonGroupItemProps {
  /**
   * Whether this item is selected
   * @default false
   */
  selected?: boolean;

  /**
   * Icon variant
   * @default 'none'
   */
  icon?: ButtonGroupItemIcon;

  /**
   * Whether the item is disabled
   * @default false
   */
  disabled?: boolean;

  /**
   * Value for selection tracking
   */
  value?: string;

  /**
   * ARIA label (required for icon-only)
   */
  ariaLabel?: string;

  /**
   * Click event handler
   */
  onClick?: (event: CustomEvent) => void;

  /**
   * Item content
   */
  children?: React.ReactNode;

  /**
   * Additional CSS classes
   */
  className?: string;

  /**
   * Additional styles
   */
  style?: React.CSSProperties;
}

export const ButtonGroupItem = forwardRef<HTMLElement, ButtonGroupItemProps>(
  (
    {
      selected = false,
      icon = 'none',
      disabled = false,
      value,
      ariaLabel,
      onClick,
      children,
      className,
      style,
    },
    ref
  ) => {
    const itemRef = useRef<HTMLElement>(null);

    useEffect(() => {
      if (ref && itemRef.current) {
        if (typeof ref === 'function') {
          ref(itemRef.current);
        } else {
          (ref as React.MutableRefObject<HTMLElement | null>).current = itemRef.current;
        }
      }
    }, [ref]);

    useEffect(() => {
      const item = itemRef.current;
      if (!item || !onClick) return;

      const handleClick = (event: Event) => {
        onClick(event as CustomEvent);
      };

      item.addEventListener('kds-button-group-item-click', handleClick);

      return () => {
        item.removeEventListener('kds-button-group-item-click', handleClick);
      };
    }, [onClick]);

    return React.createElement(
      'kds-button-group-item',
      {
        ref: itemRef,
        selected: selected || undefined,
        icon,
        disabled: disabled || undefined,
        value,
        'aria-label': ariaLabel,
        class: className,
        style,
      },
      children
    );
  }
);

ButtonGroupItem.displayName = 'ButtonGroupItem';
